name: Deploy THE-BACKDOOMS.html to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Remove all files except THE-BACKDOOMS.html
        run: |
          find . -type f ! -name 'THE-BACKDOOMS.html' -delete

      - name: Upload artifact (Only THE-BACKDOOMS.html)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
